# config/cucumber.yml
##YAML Template
---
default: --format html --out=reports/features_report.html --format pretty

html_report: --format progress --format html --out=reports/features_report.html
parallel: --format html --out reports/report<%= ENV['TEST_ENV_NUMBER']%>.html --format pretty
